### ISSUE TITLE
A question about the computation cost

### ISSUE THREAD

**Issue by speedcell4** [bytedance/1d-tokenizer#2]
Hi, thanks for sharing such a wonderful paper and its code~

I'd like to know the computation cost of training these models. 
Do you use NVIDIA A100? How many cards and how long does the training take?

Thanks ahead~

**Comment by cornettoyu** [comment]
Hi,

Please see the appendix A Training and Testing Protocols for the training costs, I attached a screenshot for reference.

<img width="923" alt="image" src="https://github.com/bytedance/1d-tokenizer/assets/138716072/cbd22a9d-c807-4b2d-87ee-32c4d4a0453e">
<img width="925" alt="image" src="https://github.com/bytedance/1d-tokenizer/assets/138716072/672d3413-7ef9-498a-9afa-a4c0df566569">
