### ISSUE TITLE
How do latent_tokens and mask tokens affect each other during training? Specifically, how does mask tokens work?

### ISSUE THREAD

**Issue by zhangqingwu** [bytedance/1d-tokenizer#26]
How do latent_tokens and mask tokens affect each other during training? Specifically, how does mask tokens work?

**Comment by Jason3900** [comment]
The latent tokens are quantized after encoder, then the output states of the corresponding latent tokens are fed into the decoder as the last part of the input, following mask tokens. In that way, the latent token's corresponding output will share the info of the image.

**Comment by cornettoyu** [comment]
Hi,

Thank you all for your interests in our work and patience. We have released the two-stage training code and feel free to check it. Hope it addresses your question on how mask tokens work.

**Comment by forever208** [comment]
Thanks for providing the code, but it is still unclear why the masked tokens are added in the decoding stage.
