### ISSUE TITLE
Difficulty in training the tokenizer

### ISSUE THREAD

**Issue by Jason3900** [bytedance/1d-tokenizer#27]
Hey, thanks for your excellent work.
I meet some difficulties in training the 1d tokenizer. I see that in large scale training without a pretrained vqgan, the codebook quickly collapse to certain tokens which causes the reconstruction process to be hard to train. How do you fix this problem to make the codebook kept in a diverse distribution?

**Comment by lxa9867** [comment]
I encountered the same issue and didn't find a solution.

**Comment by Jason3900** [comment]
OK…have you tried other quantizers?I use lfq but it still didn't work as expected. Or is there any clues to this problem, you think?
> I encountered the same issue and didn't find a solution.

**Comment by Jason3900** [comment]
> I encountered the same issue and didn't find a solution.

And have you encountered a case that all images are overlapped together during training?

**Comment by cornettoyu** [comment]
Hi,

Thank you all for your interests in our work and patience. We have released the two-stage training code and feel free to check it.
