### ISSUE TITLE
Changing resolution on the fly

### ISSUE THREAD

**Issue by elias-ramzi** [bytedance/1d-tokenizer#34]
Hi thank you for the great work and repo!

I am trying to use TiTok on images of different sizes than what the model was trained on.
Currently I am doing the following:

1. In the encoder I use use interpolated positional embedding, following timm's implementation (https://github.com/huggingface/pytorch-image-models/blob/ee5b1e8217134e9f016a0086b793c34abb721216/timm/layers/pos_embed.py#L17)
2. For the decoder there is two steps:
a. Add more masked tokens to match the image size
b. Interpolate the positional embedding to accept the increase sequence length

However the results are really bad:

![image](https://github.com/user-attachments/assets/94275500-f6ed-4465-b88b-b4cbf3ff233e)

Is this the correct approach? Have you successfully used TiTok with higher resolution without training for this resolution?

Thank you for your help!

**Comment by cornettoyu** [comment]
Hi, IMHO adapting to larger resolution without training on it is a very challenging problem for ViT architecture, especially when the task relies on dense feature map. I believe this would be interesting future direction. Perhaps you can try the [sliding window trick](https://github.com/bytedance/OmniScient-Model/blob/main/modeling/osm.py#L63) as we used in our previous model but I have not tried it.

**Comment by elias-ramzi** [comment]
Hi, thank you for your answer. I will take a look at your sliding window approach!
