### ISSUE TITLE
About Quantizer

### ISSUE THREAD

**Issue by RohollahHS** [bytedance/1d-tokenizer#35]
Hi, Congrats for the great work,

Did you try using EMA Quantizer? I think it might work better.

Thanks

**Comment by cornettoyu** [comment]
Thanks for the suggestion. Could you elaborate on the EMA quantizer? If you mean keep the EMA weight of the quantizer, I believe that is already used.

**Comment by RohollahHS** [comment]
I meant using Exponential Moving Average (EMA) for updating the codebook.

**Comment by cornettoyu** [comment]
> I meant using Exponential Moving Average (EMA) for updating the codebook.

Then it is already used, you can refer to the code [here](https://github.com/bytedance/1d-tokenizer/blob/main/utils/train_utils.py#L120)

**Comment by RohollahHS** [comment]
Oh. Thanks for the clarification.
