### ISSUE TITLE
Request for training code

### ISSUE THREAD

**Issue by ChuxiJ** [bytedance/1d-tokenizer#4]
![image](https://github.com/bytedance/1d-tokenizer/assets/30956809/10f79a15-00b7-43fd-bc9d-33e5efc564f6)

Great work!

Want to reproduce the results of your paper and do some experiments, can we get the training code?

Maybe we can replace the vq with FSQ and increase the codebook size from 4096 into bigger number so we can find a token level with optimal compact size and reconstruction quality.

Thanks!

**Comment by cornettoyu** [comment]
Hi,

Improving TiTok with FSQ or larger codebook sounds promising and interesting. The training code is still waiting for internal review and approval. Feel free to let me know if you have any questions regarding technical details before we release the full codebase.

**Comment by numb3r3** [comment]
Congrats on your remarkable work. Looking forward to the training codes.

**Comment by zimenglan-sysu-512** [comment]
will release the training code?

**Comment by yyyouy** [comment]
Thank you for your excellent work. I would like to inquire about the expected time for internal review and approval.

**Comment by cornettoyu** [comment]
Hi,

Thank you all for your interests in our work and patience. We have released the two-stage training code and feel free to check it.
