### ISSUE TITLE
About the FID reported in the RAR paper

### ISSUE THREAD

**Issue by jeasinema** [bytedance/1d-tokenizer#49]
Hi,

Thanks for open-sourcing the code and models, it's been an pleasant read:) I have a QQ on the FID reported in the paper, which can go as low as **1.48** on IN-1k 256^2. However, as indicated [here](https://github.com/google-research/maskgit?tab=readme-ov-file#running-pretrained-models), the tokenizer (MaskGIT VQ) used by RAR can only attain 2.28 **reconstruction FID** on the same setting. I am wondering if you have some insights on this or maybe I missed anything. Thank you.

Best,
XM

**Comment by cornettoyu** [comment]
Hi,

As discussed in #46 , rFID and gFID are computed differently and thus are not differently comparable (if you look at [MAR](https://arxiv.org/pdf/2406.11838)'s table2 they also report a gFID < rFID).

**Comment by jeasinema** [comment]
Thank you!
