### ISSUE TITLE
Use Titok in RAR

### ISSUE THREAD

**Issue by Doctor-James** [bytedance/1d-tokenizer#52]
Thank you for your excellent and hardcore work. 
I would like to ask if you have tried using your own tokenizer, such as titok_l32, in RAR. Does a tokenizer that is so short and one-dimensional work on RAR?

**Comment by Doctor-James** [comment]
Additionally, I would like to ask if there is any code available as a reference for preprocessing ImageNet into a tokenized and compressed JSONL format?

**Comment by cornettoyu** [comment]
Hi,

Thanks for your interests in our work.

1. For RAR + TiTok, please stay tuned :)

2. We will provide the pretokenization script soon

**Comment by RohollahHS** [comment]
> Hi,
> 
> Thanks for your interests in our work.
> 
> 1. For RAR + TiTok, please stay tuned :)
> 2. We will provide the pretokenization script soon

Hi, Great work.

I'm looking forward for the pretokenization script.

Thanks

**Comment by cornettoyu** [comment]
For pretokenization script, please see https://github.com/bytedance/1d-tokenizer/blob/main/README_RAR.md#training-preparation

**Comment by Ferry1231** [comment]
> Hi,
> 
> Thanks for your interests in our work.
> 
> 1. For RAR + TiTok, please stay tuned :)
> 2. We will provide the pretokenization script soon

Dear Researchers:

Thanks for your excellent work: RAR and TiTok! I want to conduct some experiments on RAR, and I want to use TiTok L-32 tokenizer to replace the origin tokenizer for faster training and inferencing. Looking forward to your RAR+TikTok!
