### ISSUE TITLE
About maskgitvq.jsonl

### ISSUE THREAD

**Issue by RohollahHS** [bytedance/1d-tokenizer#54]
Hi, what is `maskgitvq.jsonl`? It is needed in `PretoeknizedDataSetJSONL(dataset_config.pretokenization)`.

**Comment by cornettoyu** [comment]
Hi,

Please see https://github.com/bytedance/1d-tokenizer/blob/main/README_RAR.md#training-preparation

**Comment by RohollahHS** [comment]
Thanks, that's great.
