### ISSUE TITLE
About timesteps_embeddings

### ISSUE THREAD

**Issue by Doctor-James** [bytedance/1d-tokenizer#59]
Could you please explain the purpose of timesteps_embeddings in this code? Is it also necessary to include timesteps_embeddings in an AR model? Are there any related papers or ablation studies that support this? Thank you.
`        # seperate condition token for each step, at generation, we start from 1 to seq len

condition_token = condition_token.unsqueeze(1) + self.timesteps_embeddings[:, :x.shape[1]]
`

**Comment by cornettoyu** [comment]
Hi,

This is because adaLN was originally designed for diffusion models; We consider the token location (as in AR image is generated token by token) to mimic timestep embedding to better adapt adaLN for transformer generators. It is a straightforward adaption to use adaLN for transformer models.
