### ISSUE TITLE
Misalignment Between Ablation and Main Results for RAR-L

### ISSUE THREAD

**Issue by HansPolo113** [bytedance/1d-tokenizer#60]
Hi,

Thank you for sharing this awesome work. I noticed a potential misalignment between the ablation and main results reported in paper. 

In Tab.2, the ablation evaluates different annealing strategies, and the best FID is 2.18 for RAR-L, and the paper sates: "Therefore, we default to adopt this annealing strategy for all RAR models."

However, in main results (Tab.4), the FID for RAR-L is reported as 1.70, this make me confused about the differences between them, could you clarify what changes were made?

Looking forward to your responds.

**Comment by cornettoyu** [comment]
Hi,

The performance difference (2.18 -> 1.70) comes from different implementation details, which has been illustrated in "4.1. Implementation Details" where we illustrated the differences between ablation models and final models. In short, ablation models is smaller to speed up the experiments.

**Comment by HansPolo113** [comment]
Hi,

Thanks for the clarification, I am now understanding the differences between these two.

Best regards
