### ISSUE TITLE
Does training RAR actually require 4000 epochs?

### ISSUE THREAD

**Issue by hp-l33** [bytedance/1d-tokenizer#63]
Thank you for your excellent work and the provided codebase!

I noticed that you mentioned using ten-crop, which means that training for 1 epoch on the pretokenized dataset is equivalent to training for 10 epochs on the imagenet dataset. Does this imply that you actually trained for 4000 epochs? How many GPUs were required for training, and how long did it take?

**Comment by hp-l33** [comment]
Now I understand that when using the pretokenized dataset, the number of epochs should be set to 40.

**Comment by cornettoyu** [comment]
We configure the training by batch size (2048) and total steps (250k), thus the model will see 2048 * 250k = 512M samples, which is 512M / 1.28M = 400 ImageNet epochs. You can also say it is 40 epochs over the 10-crop version. Alternatively, you can consider 10-crop is an offline version augmentation for pre-tokenized dataset. The training for RAR-L takes ~2 days with 32 A100-40G.

**Comment by hp-l33** [comment]
Thank you for your prompt reply
