### ISSUE TITLE
Why permute NLD to LND shape? 

### ISSUE THREAD

**Issue by tau-yihouxiang** [bytedance/1d-tokenizer#7]
Why permute x's shape  from NLD to LND? This is different from the principle, which means attention in batch channel of each word.

```
x = x.permute(1, 0, 2)  # NLD -> LND
for i in range(self.num_layers):
    x = self.transformer[i](x)
x = x.permute(1, 0, 2)  # LND -> NLD
```

**Comment by MaxxP0** [comment]
because they dont use MultiHeadAttention with batch_first=True.

**Comment by tau-yihouxiang** [comment]
Thanks~
